name: Build Android APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build APK
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        uses: actions/upload-artifact@v4
        with:
          name: meine-app
          path: app/build/outputs/apk/debug/app-debug.apk
