name: Build Android APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build APK
        run: |
          if [ -f "gradlew" ]; then
            chmod +x gradlew
            ./gradlew assembleDebug
          else
            echo "FEHLER: gradlew Datei wurde im Hauptverzeichnis nicht gefunden!"
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sethic-app
          path: app/build/outputs/apk/debug/app-debug.apk
